version: "3.7"

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB}
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - takl-challenge

  node-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "8081:8080"
    expose:
      - "8081"
    networks:
      - takl-challenge

volumes:
  db_data:

networks:
  takl-challenge:
    driver: bridge